# Generated by Django 5.2.7 on 2025-10-26 10:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTrade',
            fields=[
                ('ticker', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('qty_owned', models.BigIntegerField()),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('stop_loss_amt', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'active_trades',
            },
        ),
        migrations.CreateModel(
            name='PortfolioCash',
            fields=[
                ('ticker', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('available_cash', models.DecimalField(decimal_places=4, default=Decimal('500.0'), max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'portfolio_cash',
            },
        ),
        migrations.CreateModel(
            name='StrategyState',
            fields=[
                ('ticker', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('breakout_streak', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'strategy_state',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('available_cash', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='DarvasBox',
            fields=[
                ('box_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('min_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('max_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('base_close', models.DecimalField(decimal_places=4, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'darvas_boxes',
                'indexes': [models.Index(fields=['ticker'], name='darvas_boxe_ticker_f29d4f_idx'), models.Index(fields=['start_date'], name='darvas_boxe_start_d_895544_idx'), models.Index(fields=['end_date'], name='darvas_boxe_end_dat_d1d661_idx')],
            },
        ),
        migrations.CreateModel(
            name='Historicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('ticker', models.CharField(max_length=50)),
                ('close', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('open', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historicals',
                'indexes': [models.Index(fields=['ticker'], name='historicals_ticker_5e0801_idx'), models.Index(fields=['trade_date'], name='historicals_trade_d_a3e622_idx')],
                'constraints': [models.UniqueConstraint(fields=('ticker', 'trade_date'), name='historicals_unique')],
            },
        ),
        migrations.CreateModel(
            name='SimulationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('ticker', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('log_type', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], default='INFO', max_length=10)),
            ],
            options={
                'db_table': 'simulation_log',
                'indexes': [models.Index(fields=['ticker'], name='simulation__ticker_6c105b_idx'), models.Index(fields=['log_date'], name='simulation__log_dat_b224ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateField()),
                ('ticker', models.CharField(max_length=50)),
                ('txn_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('qty', models.BigIntegerField()),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['ticker'], name='transaction_ticker_c4baff_idx'), models.Index(fields=['txn_date'], name='transaction_txn_dat_d74e33_idx')],
            },
        ),
    ]
