# Generated by Django 5.2.7 on 2025-10-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffet_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
                ('order_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('qty', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trading_plan',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=50)),
                ('order_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('qty', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FILLED', 'FILLED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
                'indexes': [models.Index(fields=['ticker'], name='orders_ticker_802cbe_idx'), models.Index(fields=['status'], name='orders_status_762191_idx'), models.Index(fields=['created_at'], name='orders_created_77e2b9_idx')],
            },
        ),
    ]
